{
 "title": "StorageOS-1.2",
 "description": "StorageOS example dashboard with metric names updated for StorageOS v1.2.0+ compatibility. ",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "10s,20s,30s,60s,90s,120s" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(exported_namespace)"
   },
   {
    "name": "volume_name",
    "label": "Volume Name",
    "query": "label_values(storageos_volume_size_bytes{exported_namespace=~\"$namespace\"}, volume_name)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(storageos_node_device_capacity_bytes, instance)"
   }
  ]
 },
 "panels": [
  { "title": "StorageOS Node Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "StorageOS Process Uptime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s", "label": "Process Uptime" }
   ],
   "targets": [
    {
     "expr": "time() - storageos_control_process_start_time_seconds{instance=~\"$node\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Volumes Per Node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(storageos_node_volumes_total{instance=~\"$node\"}) by (instance, volume_type)",
     "legendFormat": "{{ instance }} {{ volume_type }}s"
    }
   ]
  },
  {
   "title": "Total Read/Write rate (IOPS)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(storageos_volume_frontend_write_total{instance=~\"$node\"}[2m])) by (instance)",
     "legendFormat": "{{ instance }} writes"
    },
    {
     "expr": "sum(rate(storageos_volume_frontend_read_total{instance=~\"$node\"}[2m])) by (instance)",
     "legendFormat": "{{ instance }} reads"
    }
   ]
  },
  {
   "title": "Total Read/Write Bandwidth",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(storageos_volume_frontend_write_bytes_total{instance=~\"$node\"}[2m])) by (instance)",
     "legendFormat": "{{ instance }} writes"
    },
    {
     "expr": "sum(rate(storageos_volume_frontend_read_bytes_total{instance=~\"$node\"}[2m])) by (instance)",
     "legendFormat": "{{ instance }} reads"
    }
   ]
  },
  {
   "title": "StorageOS CPU and Resident Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percent", "label": "CPU Used/s" }
   ],
   "targets": [
    {
     "expr": "(rate(storageos_control_process_cpu_seconds_total{instance=~\"$node\"}[3m]) +\nrate(storageos_dataplane_process_cpu_seconds_total{instance=~\"$node\"}[3m]) +\nrate(storageos_stats_process_cpu_seconds_total{instance=~\"$node\"}[3m])) * 100",
     "legendFormat": "{{ instance }} CPU used"
    },
    {
     "expr": "storageos_control_process_resident_memory_bytes{instance=~\"$node\"} +\nstorageos_dataplane_process_resident_memory_bytes{instance=~\"$node\"} +\nstorageos_stats_process_resident_memory_bytes{instance=~\"$node\"}",
     "legendFormat": "{{ instance }} resident memory used"
    }
   ]
  },
  {
   "title": "StorageOS Namespace Read/Write Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 }
  },
  {
   "title": "Frontend Volume IOPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(storageos_volume_frontend_write_total{exported_namespace=~\"$namespace\"}[2m])) by (volume_name)",
     "legendFormat": "{{ volume_name }} writes"
    },
    {
     "expr": "sum(rate(storageos_volume_frontend_read_total{exported_namespace=~\"$namespace\"}[2m])) by (volume_name)",
     "legendFormat": "{{ volume_name }} reads"
    }
   ]
  },
  {
   "title": "Frontend Volume Read/Write Bandwidth",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(storageos_volume_frontend_write_bytes_total{exported_namespace=~\"$namespace\"}[2m])) by (volume_name)",
     "legendFormat": "{{ volume_name }} Writes"
    },
    {
     "expr": "sum(rate(storageos_volume_frontend_read_bytes_total{exported_namespace=~\"$namespace\"}[2m])) by (volume_name)",
     "legendFormat": "{{ volume_name }} Reads"
    }
   ]
  }
 ]
}