{
 "title": "etcd-clusters-as-service",
 "description": "Server Etcd Dashboard from Prometheus",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster", "query": "label_values(job)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values({job=\"$cluster\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Info",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(etcd_mvcc_db_total_size_in_bytes{instance=~\"$instance\",job=~\"$cluster\"} / etcd_server_quota_backend_bytes{instance=~\"$instance\",job=~\"$cluster\"})*100"
    },
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\",job=~\"$cluster\"}"
    },
    {
     "expr": "sum(etcd_debugging_mvcc_keys_total{instance=~\"$instance\",job=~\"$cluster\"}) by (instance)"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{instance=~\"$instance\",job=~\"$cluster\"}[5m])) by (instance, le))"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{instance=~\"$instance\",job=~\"$cluster\"}[5m])) by (instance, le))"
    },
    {
     "expr": "sum(etcd_server_is_leader{instance=~\"$instance\",job=~\"$cluster\"}) by (instance)"
    },
    {
     "expr": "sum(etcd_debugging_mvcc_db_compaction_keys_total{instance=~\"$instance\",job=~\"$cluster\"}) by (instance)"
    }
   ]
  },
  {
   "title": "Etcd has a leader?",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(etcd_server_has_leader{instance=~\"$instance\",job=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Etcd Members",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(etcd_server_id{instance=~\"$instance\",job=~\"$cluster\"})",
     "legendFormat": "members"
    }
   ]
  },
  {
   "title": "DB Info per Member",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "% DB Space Used $instance",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
     "repeat": "instance",
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "(etcd_mvcc_db_total_size_in_bytes{instance=~\"$instance\",job=~\"$cluster\"} / etcd_server_quota_backend_bytes{instance=~\"$instance\",job=~\"$cluster\"})*100"
      }
     ]
    },
    {
     "title": "% DB Space Used $instance",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "(etcd_mvcc_db_total_size_in_bytes{instance=~\"$instance\",job=~\"$cluster\"} / etcd_server_quota_backend_bytes{instance=~\"$instance\",job=~\"$cluster\"})*100"
      }
     ]
    },
    {
     "title": "% DB Space Used $instance",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "(etcd_mvcc_db_total_size_in_bytes{instance=~\"$instance\",job=~\"$cluster\"} / etcd_server_quota_backend_bytes{instance=~\"$instance\",job=~\"$cluster\"})*100"
      }
     ]
    },
    {
     "title": "Urgent Defragmentation ? $instance",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 14 },
     "repeat": "instance",
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "(etcd_mvcc_db_total_size_in_bytes{instance=~\"$instance\",job=~\"$cluster\"} / etcd_server_quota_backend_bytes{instance=~\"$instance\",job=~\"$cluster\"})*100"
      }
     ]
    },
    {
     "title": "Urgent Defragmentation ? $instance",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 14 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "(etcd_mvcc_db_total_size_in_bytes{instance=~\"$instance\",job=~\"$cluster\"} / etcd_server_quota_backend_bytes{instance=~\"$instance\",job=~\"$cluster\"})*100"
      }
     ]
    },
    {
     "title": "Urgent Defragmentation ? $instance",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 14 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "(etcd_mvcc_db_total_size_in_bytes{instance=~\"$instance\",job=~\"$cluster\"} / etcd_server_quota_backend_bytes{instance=~\"$instance\",job=~\"$cluster\"})*100"
      }
     ]
    },
    {
     "title": "DB Left capacity (with fragmented space) $instance",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
     "repeat": "instance",
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "etcd_server_quota_backend_bytes{instance=~\"$instance\",job=~\"$cluster\"} - etcd_mvcc_db_total_size_in_bytes{instance=~\"$instance\",job=~\"$cluster\"}",
       "legendFormat": "Backend bytes - DB Size"
      }
     ]
    },
    {
     "title": "DB Left capacity (with fragmented space) $instance",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "etcd_server_quota_backend_bytes{instance=~\"$instance\",job=~\"$cluster\"} - etcd_mvcc_db_total_size_in_bytes{instance=~\"$instance\",job=~\"$cluster\"}",
       "legendFormat": "Backend bytes - DB Size"
      }
     ]
    },
    {
     "title": "DB Left capacity (with fragmented space) $instance",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "etcd_server_quota_backend_bytes{instance=~\"$instance\",job=~\"$cluster\"} - etcd_mvcc_db_total_size_in_bytes{instance=~\"$instance\",job=~\"$cluster\"}",
       "legendFormat": "Backend bytes - DB Size"
      }
     ]
    },
    {
     "title": "DB Size Limit (Backend-bytes) $instance",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 25 },
     "repeat": "instance",
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "etcd_server_quota_backend_bytes{instance=~\"$instance\",job=~\"$cluster\"}",
       "legendFormat": "{{ instance }} Quota Bytes"
      }
     ]
    },
    {
     "title": "DB Size Limit (Backend-bytes) $instance",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 25 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "etcd_server_quota_backend_bytes{instance=~\"$instance\",job=~\"$cluster\"}",
       "legendFormat": "{{ instance }} Quota Bytes"
      }
     ]
    },
    {
     "title": "DB Size Limit (Backend-bytes) $instance",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 25 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "etcd_server_quota_backend_bytes{instance=~\"$instance\",job=~\"$cluster\"}",
       "legendFormat": "{{ instance }} Quota Bytes"
      }
     ]
    }
   ]
  },
  { "title": "General Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Keys",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_debugging_mvcc_keys_total{instance=~\"$instance\",job=~\"$cluster\"}",
     "legendFormat": "{{ instance }} Num keys"
    }
   ]
  },
  {
   "title": "Client Traffic In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_received_bytes_total{instance=~\"$instance\",job=~\"$cluster\"}[5m])",
     "legendFormat": "{{ instance }} Client Traffic In"
    }
   ]
  },
  {
   "title": "Client Traffic Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_sent_bytes_total{instance=~\"$instance\",job=~\"$cluster\"}[5m])",
     "legendFormat": "{{ instance }} Client Traffic Out"
    }
   ]
  },
  {
   "title": "Peer Traffic In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_received_bytes_total{instance=~\"$instance\",job=~\"$cluster\"}[5m])) by (instance)",
     "legendFormat": "{{ instance }} Peer Traffic In"
    }
   ]
  },
  {
   "title": "Peer Traffic Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_sent_bytes_total{instance=~\"$instance\",job=~\"$cluster\"}[5m])) by (instance)",
     "legendFormat": "{{ instance }} Peer Traffic Out"
    }
   ]
  },
  {
   "title": "Key Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_debugging_mvcc_put_total{instance=~\"$instance\",job=~\"$cluster\"}[5m])",
     "legendFormat": "{{ instance }} puts/s"
    },
    {
     "expr": "rate(etcd_debugging_mvcc_delete_total{instance=~\"$instance\",job=~\"$cluster\"}[5m])",
     "legendFormat": "{{ instance }} deletes/s"
    }
   ]
  },
  {
   "title": "Members",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(etcd_server_id{instance=~\"$instance\",job=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Slow operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_server_slow_apply_total{instance=~\"$instance\",job=~\"$cluster\"}",
     "legendFormat": "{{ instance }} slow applies"
    },
    {
     "expr": "etcd_server_slow_read_indexes_total{instance=~\"$instance\",job=~\"$cluster\"}",
     "legendFormat": "{{ instance }} slow read indexes"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\",job=~\"$cluster\"}",
     "legendFormat": "{{ instance }} Resident Memory"
    }
   ]
  },
  {
   "title": "The total number of failed proposals seen",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 30 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(etcd_server_leader_changes_seen_total{instance=~\"$instance\",job=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_server_heartbeat_send_failures_total{instance=~\"$instance\",job=~\"$cluster\"}",
     "legendFormat": "{{ instance }} heartbeat  failures"
    },
    {
     "expr": "etcd_server_health_failures{instance=~\"$instance\",job=~\"$cluster\"}",
     "legendFormat": "{{ instance }} health failures"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "etcd_mvcc_db_total_size_in_bytes{instance=~\"$instance\",job=~\"$cluster\"}",
     "legendFormat": "{{ instance }} DB Size"
    },
    {
     "expr": "etcd_mvcc_db_total_size_in_use_in_bytes{instance=~\"$instance\",job=~\"$cluster\"}",
     "legendFormat": "{{ instance }} Used bytes"
    }
   ]
  },
  {
   "title": "The number of leader changes seen",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 36 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(etcd_server_leader_changes_seen_total{instance=~\"$instance\",job=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Raft Proposals",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_server_proposals_failed_total{instance=~\"$instance\",job=~\"$cluster\"}[5m]))",
     "legendFormat": "Proposal Failure Rate"
    },
    {
     "expr": "sum(etcd_server_proposals_pending{instance=~\"$instance\",job=~\"$cluster\"})",
     "legendFormat": "Proposal Pending Total"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_committed_total{instance=~\"$instance\",job=~\"$cluster\"}[5m]))",
     "legendFormat": "Proposal Commit Rate"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_applied_total{instance=~\"$instance\",job=~\"$cluster\"}[5m]))",
     "legendFormat": "Proposal Apply Rate"
    }
   ]
  },
  {
   "title": "Defrag time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_disk_backend_defrag_duration_seconds_sum{instance=~\"$instance\",job=~\"$cluster\"}[1m])",
     "legendFormat": "{{ instance }} latency distributions of defrag"
    }
   ]
  },
  {
   "title": "Proposals pending",
   "type": "graph",
   "description": "indicates how many proposals are queued to commit. Rising pending proposals suggests there is a high client load or the member cannot commit proposals.",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(etcd_server_proposals_pending{instance=~\"$instance\",job=~\"$cluster\"})",
     "legendFormat": "Proposals pending"
    }
   ]
  },
  {
   "title": "Compacted Keys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_debugging_mvcc_db_compaction_keys_total{instance=~\"$instance\",job=~\"$cluster\"}",
     "legendFormat": "{{ instance  }} keys compacted "
    }
   ]
  },
  {
   "title": "Total Leader Elections Per Day",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "changes(etcd_server_leader_changes_seen_total{instance=~\"$instance\",job=~\"$cluster\"}[1d])",
     "legendFormat": "{{ instance }} Total Leader Elections Per Day"
    }
   ]
  },
  {
   "title": "The total number of consensus proposals committed",
   "type": "graph",
   "description": "proposals_committed_total records the total number of consensus proposals committed. This gauge should increase over time if the cluster is healthy. Several healthy members of an etcd cluster may have different total committed proposals at once. This discrepancy may be due to recovering from peers after starting, lagging behind the leader, or being the leader and therefore having the most commits. It is important to monitor this metric across all the members in the cluster; a consistently large lag between a single member and its leader indicates that member is slow or unhealthy.\n\nproposals_applied_total records the total number of consensus proposals applied. The etcd server applies every committed proposal asynchronously. The difference between proposals_committed_total and proposals_applied_total should usually be small (within a few thousands even under high load). If the difference between them continues to rise, it indicates that the etcd server is overloaded. This might happen when applying expensive queries like heavy range queries or large txn operations.",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_server_proposals_committed_total{instance=~\"$instance\",job=~\"$cluster\"}[5m]))",
     "legendFormat": "total number of consensus proposals committed"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_applied_total{instance=~\"$instance\",job=~\"$cluster\"}[5m]))",
     "legendFormat": "total number of consensus proposals applied"
    }
   ]
  },
  {
   "title": "Disks operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_disk_wal_fsync_duration_seconds_sum{instance=~\"$instance\",job=~\"$cluster\"}[1m])",
     "legendFormat": "{{ instance }} The latency distributions of fsync called by wal"
    },
    {
     "expr": "rate(etcd_disk_backend_commit_duration_seconds_sum{instance=~\"$instance\",job=~\"$cluster\"}[1m])",
     "legendFormat": "{{ instance }} The latency distributions of commit called by backend"
    }
   ]
  },
  {
   "title": "RPC Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{grpc_type=\"unary\",instance=~\"$instance\",job=~\"$cluster\"}[5m]))",
     "legendFormat": "RPC Rate"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_type=\"unary\",grpc_code!=\"OK\",instance=~\"$instance\",job=~\"$cluster\"}[5m]))",
     "legendFormat": "RPC Failed Rate"
    }
   ]
  },
  {
   "title": "Active Streams",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(grpc_server_started_total{grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\",instance=~\"$instance\",job=~\"$cluster\"}) - sum(grpc_server_handled_total{grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\",instance=~\"$instance\",job=~\"$cluster\"})",
     "legendFormat": "Watch Streams"
    },
    {
     "expr": "sum(grpc_server_started_total{grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\",instance=~\"$instance\",job=~\"$cluster\"}) - sum(grpc_server_handled_total{grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\",instance=~\"$instance\",job=~\"$cluster\"})",
     "legendFormat": "Lease Streams"
    }
   ]
  },
  {
   "title": "Compaction rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_debugging_mvcc_db_compaction_keys_total{instance=~\"$instance\",job=~\"$cluster\"}[5m])",
     "legendFormat": "{{ instance }} compact/s"
    }
   ]
  },
  {
   "title": "Snapshot duration",
   "type": "graph",
   "description": "Abnormally high snapshot duration (snapshot_save_total_duration_seconds) indicates disk issues and might cause the cluster to be unstable.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_debugging_snap_save_total_duration_seconds_sum{instance=~\"$instance\",job=~\"$cluster\"}[1m]))",
     "legendFormat": "The total latency distributions of save called by snapshot"
    }
   ]
  },
  {
   "title": "Disk Sync Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{instance=~\"$instance\",job=~\"$cluster\"}[5m])) by (instance, le))",
     "legendFormat": "{{ instance }} WAL fsync"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{instance=~\"$instance\",job=~\"$cluster\"}[5m])) by (instance, le))",
     "legendFormat": "{{ instance }} DB fsync"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_client_grpc_received_bytes_total{instance=~\"$instance\",job=~\"$cluster\"}[1m]))",
     "legendFormat": "The total number of bytes received by grpc clients"
    },
    {
     "expr": "sum(rate(etcd_network_client_grpc_sent_bytes_total{instance=~\"$instance\",job=~\"$cluster\"}[1m]))",
     "legendFormat": "The total number of bytes sent to grpc clients"
    }
   ]
  }
 ]
}