apiVersion: v1
kind: Service
metadata:
  labels:
    app: etcd
    cluster: adhoc
  name: adhoc-etcd
  namespace: etcd
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: 2379
    targetPort: 2379
  selector: null
